### ISSUE TITLE
Tinky Winky Bag doesn't work

### ISSUE THREAD

**Issue by SoyJetixXD** [Rexbas/Teletubbies-Mod#10]
Hello, I am using the latest available version of Teletubbies (4.0.0) in 1.12.2, everything is fine except something, and that is that the Tinky Winky bag does not work, you can not open or store objects ...
Is this a bug?
Thank you for reading

**Comment by Rexbas** [comment]
It's not a bug. Somewhere in Minecraft 1.10 or 1.11 I disabled the functionality of the bag because of bugs. I never fixed it until yesterday. In Teletubbies-1.14.4-5.2.0 the bag works. Today I will try to get it working on 1.12 as it is still a well downloaded version.

**Comment by Rexbas** [comment]
It appears that things work a little different on 1.12 so I decided to not fix the Tinky Winky Bag for 1.12
