### ISSUE TITLE
[Request] Add config options for spawn rates

### ISSUE THREAD

**Issue by HariboTer** [Rexbas/Teletubbies-Mod#14]
This is a wonderful mod that is only tainted by the problem that the unique, mysterious and legendary Tubby Hill structure is spawning much too often and not rarely are even two of them overlapping into each other. I would like to keep their ominous feeling by making them generate more seldomly and for similar reasons also reduce the spawn chance of the (zombified) Teletubbies.

TL;DR: Please provide a config file with options for the Tubby Hill structure, Teletubby and Zombie Teletubby spawn rates so that they can be adjusted

**Comment by Rexbas** [comment]
I will take a look

**Comment by Rexbas** [comment]
In the newest version (1.14.4-5.4.0 and 1.15.2-6.2.0) I have added a config file to adjust all kind of things. However, I have not managed to add the Tubby hill structure spawn rate. So I will leave this issue open and maybe in another update I will fix it.
