### ISSUE TITLE
Tinky Winky bag looses stacks of items

### ISSUE THREAD

**Issue by PanHandle** [Rexbas/Teletubbies-Mod#22]
When the size of a stack inside a Tinky Winky bag is increased it is not stored when reopened.

Example: 
The bag contains 3 cobble, player adds 5 more to the same item slot and closes the bag.
When the bag is opened, there is still 3 cobble. 

Temporary solution found by my players is to move the stack to a new item slot before closing the bag

**Comment by jackstrain** [comment]
I'm reproducing the bug slightly differently.

Adding any amount of items to a stack of 2 or more removes one item upon opening the bag.

I'm running version 7.3.1 of the mod on MC 1.16.3.

Video of the issue if it helps: https://www.youtube.com/watch?v=TDYF7MShz7A
