### ISSUE TITLE
Suggestion: Peek at items in Tinky Winky bag

### ISSUE THREAD

**Issue by roguesensei** [Rexbas/Teletubbies-Mod#29]
Been using this mod a lot in our server and frequently use Tinky Winky bags for efficient storage, though there's no easy way to tell what items are inside besides naming the bag or storing it in a certain chest.

As a suggestion for the Tinky Winky bags, perhaps display the contents of the bag like shulker's do:
![Screenshot_2021-05-27_21-49-43](https://user-images.githubusercontent.com/32780495/119895058-e0728580-bf2c-11eb-922d-4f5a2f012f92.png)

**Comment by Rexbas** [comment]
Good idea. I will try to implement it the next time I work on the mod.
