### ISSUE TITLE
Suggestion: Game rule for full grass

### ISSUE THREAD

**Issue by roguesensei** [Rexbas/Teletubbies-Mod#35]
We've discovered a lag bottleneck on our server regarding the `teletubbies:full_grass`, as it spreads it causes frame drops exponentially. Could we have a game rule to stop the grass from spreading?

**Comment by Rexbas** [comment]
Are you sure the spread is causing lag? How big is the area or how long has the full_grass been spreading? I don't seem to have any lag on my test server.

Have you tried disabling invasive_grass in the server's config file? It will disable the spread to vanilla grass.

**Comment by roguesensei** [comment]
We've disabled it and not much has changed, but we don't think it's `full_grass` that's causing it after all. Thanks for your help.
